-- Update commodity tokens with correct market tickers
UPDATE public.commodity_tokens SET ticker = 'GC' WHERE symbol = 'GOLD' OR symbol = 'GOLD_SOL';
UPDATE public.commodity_tokens SET ticker = 'SI' WHERE symbol = 'SILVER' OR symbol = 'SILVER_SOL';
UPDATE public.commodity_tokens SET ticker = 'HG' WHERE symbol = 'COPPER' OR symbol = 'COPPER_SOL';
UPDATE public.commodity_tokens SET ticker = 'CL' WHERE symbol = 'OIL' OR symbol = 'OIL_SOL';
UPDATE public.commodity_tokens SET ticker = 'ZW' WHERE symbol = 'WHEAT' OR symbol = 'WHEAT_SOL';
UPDATE public.commodity_tokens SET ticker = 'ZC' WHERE symbol = 'CORN' OR symbol = 'CORN_SOL';
UPDATE public.commodity_tokens SET ticker = 'ZS' WHERE symbol = 'SOYBEANS' OR symbol = 'SOYBEANS_SOL';
UPDATE public.commodity_tokens SET ticker = 'NG' WHERE symbol = 'NATGAS' OR symbol = 'NATGAS_SOL';
UPDATE public.commodity_tokens SET ticker = 'PL' WHERE symbol = 'PLATINUM' OR symbol = 'PLATINUM_SOL';
UPDATE public.commodity_tokens SET ticker = 'PA' WHERE symbol = 'PALLADIUM';
UPDATE public.commodity_tokens SET ticker = 'KC' WHERE symbol = 'COFFEE' OR symbol = 'COFFEE_SOL';
UPDATE public.commodity_tokens SET ticker = 'SB' WHERE symbol = 'SUGAR' OR symbol = 'SUGAR_SOL';
UPDATE public.commodity_tokens SET ticker = 'CT' WHERE symbol = 'COTTON' OR symbol = 'COTTON_SOL';
UPDATE public.commodity_tokens SET ticker = 'ALI' WHERE symbol = 'ALUMINUM' OR symbol = 'ALUMINUM_SOL';
UPDATE public.commodity_tokens SET ticker = 'ZN' WHERE symbol = 'ZINC' OR symbol = 'ZINC_SOL';
UPDATE public.commodity_tokens SET ticker = 'NI' WHERE symbol = 'NICKEL' OR symbol = 'NICKEL_SOL';
UPDATE public.commodity_tokens SET ticker = 'CC' WHERE symbol = 'COCOA';
UPDATE public.commodity_tokens SET ticker = 'ZO' WHERE symbol = 'OATS';
UPDATE public.commodity_tokens SET ticker = 'ZR' WHERE symbol = 'RICE';
UPDATE public.commodity_tokens SET ticker = 'RB' WHERE symbol = 'GASOLINE';
UPDATE public.commodity_tokens SET ticker = 'HO' WHERE symbol = 'HEATING_OIL';
UPDATE public.commodity_tokens SET ticker = 'LBS' WHERE symbol = 'LUMBER';
UPDATE public.commodity_tokens SET ticker = 'HE' WHERE symbol = 'LEAN_HOGS';
UPDATE public.commodity_tokens SET ticker = 'LE' WHERE symbol = 'LIVE_CATTLE';
UPDATE public.commodity_tokens SET ticker = 'GF' WHERE symbol = 'FEEDER_CATTLE';
UPDATE public.commodity_tokens SET ticker = 'OJ' WHERE symbol = 'ORANGE_JUICE';
UPDATE public.commodity_tokens SET ticker = 'LTH' WHERE symbol = 'LITHIUM';
UPDATE public.commodity_tokens SET ticker = 'UX' WHERE symbol = 'URANIUM';
UPDATE public.commodity_tokens SET ticker = 'TSI' WHERE symbol = 'IRON_ORE';
UPDATE public.commodity_tokens SET ticker = 'SN' WHERE symbol = 'TIN';
UPDATE public.commodity_tokens SET ticker = 'PB' WHERE symbol = 'LEAD';
UPDATE public.commodity_tokens SET ticker = 'CO' WHERE symbol = 'COBALT';
UPDATE public.commodity_tokens SET ticker = 'MO' WHERE symbol = 'MOLYBDENUM';
UPDATE public.commodity_tokens SET ticker = 'XRH' WHERE symbol = 'RHODIUM';
UPDATE public.commodity_tokens SET ticker = 'XPD' WHERE symbol = 'IRIDIUM';
UPDATE public.commodity_tokens SET ticker = 'RU' WHERE symbol = 'RUBBER';
UPDATE public.commodity_tokens SET ticker = 'HR' WHERE symbol = 'STEEL';
UPDATE public.commodity_tokens SET ticker = 'ZB' WHERE symbol = 'BARLEY';
UPDATE public.commodity_tokens SET ticker = 'D6' WHERE symbol = 'ETHANOL';