// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntrdrgkglyutuzlvnqpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cmRyZ2tnbHl1dHV6bHZucXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzc4MDEsImV4cCI6MjA2MDMxMzgwMX0.PL_CWr5ik8nfdrziyS_mU0318HtcDH3PuEYyPvZuKNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});